"""

Django settings for CottonMonitoring project.
Generated by 'django-admin startproject' using Django 4.2.4.
For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/

"""

from pathlib import Path
import ee
import os
import dotenv 

config = {
  "type": "service_account",
  "project_id": "cotton-monitoring-cloud",
  "private_key_id": "2d1f42d896bcbd7e573694964eecc475626ebb5d",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDJIm00ccko68bf\ncsMc1wJdfKEKrZRuZs3msw4ET2NokxU+bOc8wr3e13kvUxn4hI0cQtRN/QoklPTJ\nTh+2dvW5yYVumeMSRo7L3oifc1iKofKTuW8DhZSVW8e0Te93qoyCxWmTfyr/UBlX\nICEr9RPjUalaVvWPx7l+i419r0EykPHE9/uhwGfINYZg5SCcSKYMR5fdecz3xxbU\nB02eqWo4lNd6vEE34ehQlH2U2/rDoAadDIDwoahmC8gH8xYLBnyr0j9quPliBr4l\nBe1LoZIu0IFVMqNyIAUS99p1s02XTvINAjPEeuuXVyUjsPA1uqzlAAcgMPhUT3yE\nil+grSuFAgMBAAECggEAAplb1uZPF3xo51iLUqQONLCVF9c0UpTKFSM4nGJv0Trw\nfWp3NpdXNXNCP2TA2tFkuYQo7craQay037KjgV/4hbLx7EZL5rCHnbGxzqIWzv9g\nymAoFHsEi7E6eejNEKp1SVzkzGMNvgArQzzgZDn/HYFE0nbKuvd1ZWiDxP76k4P3\noKGk1X5dHlhYCk1c4wEGGWoAjq3ji82bBWeaHpSb8S32ALWSKF37r3DfHDfkaR5w\nnWFfDhR5Nct4TiTcWBEac6FPe0aTHRaCKodhzGpXk21C97O3mDmxZfA1lirr45Jm\n9NYKgB8LHhX3xQ7HrlbCDIHTEUB1sc2NtoQTwuB3SwKBgQDt5dAn6nqW/VVQUeXf\nWbbG18teqDLdXL1x6TnteQ6w9sdQ3DPsYqZzge3pGdEcG0ObNijY+NKjFdJdZsi1\n2R7P1D8hf821+PUPjLt9JzPHdB8/AWMak3SvSi8rfy59yw4863pZRPyBIsULxdBB\nLvphc4UpG3ejU2HKnoU0C8vI3wKBgQDYcHmhfoJ6dxzvPyd3TouWifaCLBjtfLsi\nOrJopLIvIGe79C+HtUAWDeRHi2Ol/aTh9DjbnFdkqRdEa0agqxVlGtm3MUepjykW\noIqdlDGnmy8dhcq0K5xTkKD9B+HUEFK/t/n8UkWyMb0fpsEcFdousXwDnVco3pFC\nyzg2mOSEGwKBgQCeGZamkFv8MEwcXvEn6BViPFN5isqS9mkoZNkMiuFKlhaMFGul\nc0IvjW+w9GlWBoB9jBbFa0eA/qWZUQ+eWrbxY5q5BpiNkPA770lCuWTd7rw9QQy9\nwrVPMTv76j/ZdbL2pX/gB8rPf234jvQB/diEHyOl2A1AS8+3unXHyvcZfQKBgEuS\ngjWsOZzPKFA1Ke+TglPO2j67bPzHN4QNIKw/DWQ9GVtcOJhW5giNUy7T8bhMpxyq\nLIwpu64PCGvAVUnWUsMZq/k2AMKolP0skxnQW8IdAkd5prxgGdZnwn53GRf1lx8P\n+v5qL6G3kkSR8g1/Z84z9IxCjONdSzUaRgdyPSAPAoGAfLFAP9WBLsFPnlig5Qjd\nFxHbdV0qhHQsdXNUum3vsJTbqR1/ipAKYsv/gZxkZ0tebe2gEdHAuZuHPHzL1Wuh\nnBLbHD86HoYM0OZ3wS5iZ4k7RfuFv1nVYLWY1HRqdCelDQC/uk8xPOOivWBhm/Vy\n1mp/igzXrHTgZDVtvusyoAI=\n-----END PRIVATE KEY-----\n",
  "client_email": "aneeqgee@cotton-monitoring-cloud.iam.gserviceaccount.com",
  "client_id": "100292290513069523501",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/aneeqgee%40cotton-monitoring-cloud.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}


service_account = 'aneeqgee@cotton-monitoring-cloud.iam.gserviceaccount.com'
credentials = ee.ServiceAccountCredentials(service_account, str(config))
ee.Initialize(credentials)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

dotenv_file = os.path.join(BASE_DIR, ".env")
if os.path.isfile(dotenv_file):
    dotenv.load_dotenv(dotenv_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']



ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'users',
    'api',
    'background_task'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CottonMonitoring.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CottonMonitoring.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': os.environ['ENGINE'],
        'NAME': os.environ['NAME'],
        'USER': os.environ['USER'],
        'HOST': os.environ['HOST'],
        'PASSWORD': os.environ['PASSWORD'],
        'Port' : os.environ['Port']
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
#
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

APPEND_SLASH=False